version: '3'
services:
  postsql:
    image: postgres:9.6.1-alpine
    env_file:
      - .postgres.env
    volumes:
        - postgres:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
volumes:
  postgres:
